version: '3.2'

services:
  dotnet:
    # container_name: dotenet
    build:
      context: .
      dockerfile: Dockerfile
    # image: nginx
    restart: always
    networks:
      network:
    deploy:
      mode: replicated
      replicas: 3
      endpoint_mode: dnsrr

networks:
  network:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1
