    pipeline {
    agent any
   
    stages {
        stage('dotnet test') {
          steps{
            script {
                sh "dotnet test"
            }
          }
        }
        
        stage('dotnet deploy') {      	
            steps{                       	
            	sh 'cd AspnetCore6ApiTestingDemo && ls && sudo docker-compose up --build -d'
            	echo 'docker container build and deployed '      
            }           
        } 
  }
}
